pxc-mysql: support deploying with mysql_version="8.4"
- Allow mysql_version="8.4"; previously only "5.7" or "8.0" were allowed

- Enable mysql_native_password for MySQL v8.4; This authentication
  method was deprecated in MySQL v8.0 and disabled by default in v8.4
  and completely removed as of MySQL v9.0+

- Handle upgrading from crashed MySQL v8.0 instances to MySQL v8.4

- Remove deprecated binlog_format option;  This has defaulted to ROW for
  several major versions now and was deprecated in MySQL v8.0.

NOTE: As of this commit, mysql_version=8.4 does not support the audit log
      at all and attempting to deploy with audit logging enabled will
      fail.

diff --git a/jobs/pxc-mysql/templates/pre-start.sh.erb b/jobs/pxc-mysql/templates/pre-start.sh.erb
--- a/jobs/pxc-mysql/templates/pre-start.sh.erb
+++ b/jobs/pxc-mysql/templates/pre-start.sh.erb
@@ -5,10 +5,12 @@ set -e
 set -o pipefail
 
 <%-
-  unless %w[5.7 8.0].include? p('mysql_version')
-    raise "Unsupported value '#{p('mysql_version')}' for 'mysql_version' property. Choose from '8.0' or '5.7'"
+  unless %w[5.7 8.0 8.4].include? p('mysql_version')
+    raise "Unsupported value '#{p('mysql_version')}' for 'mysql_version' property. Choose from '8.4', '8.0' or '5.7'"
   end
 -%>
+
+mysql_version="<%=p('mysql_version')%>"
 
 ## NOTE: This script MUST ALWAYS run as root user.
 
@@ -59,13 +61,13 @@ chown -R vcap:vcap ${MYSQL_RUN_DIR}
 
 log "pre-start setup script: set up ENV and logging"
 
-<% if p('engine_config.audit_logs.enabled') %>
+<%- if p('engine_config.audit_logs.enabled') -%>
 mkdir -p ${SERVER_AUDIT_LOG_DIR}
 chown vcap:vcap ${SERVER_AUDIT_LOG_DIR}
 
 # logrotate audit logs
 ln -sf /var/vcap/jobs/pxc-mysql/config/mysql_clustered_audit_logs.logrotate /etc/logrotate.d/mysql_clustered_audit_logs
-<% end %>
+<%- end -%>
 
 # logrotate mysql_slow_query
 ln -sf /var/vcap/jobs/pxc-mysql/config/mysql_slow_query_logs.logrotate /etc/logrotate.d/mysql_slow_query_logs
@@ -86,7 +88,7 @@ chown -R vcap:vcap ${LOG_DIR}
 # add mysql to path
 if [[ ! -f /usr/local/bin/mysql ]]; then
   log "Adding mysql to path"
-  ln -sf /var/vcap/packages/percona-xtradb-cluster-<%= p('mysql_version') %>/bin/mysql /usr/local/bin
+  ln -sf "/var/vcap/packages/percona-xtradb-cluster-${mysql_version}/bin/mysql" /usr/local/bin
 fi
 
 
@@ -105,7 +107,7 @@ ln -sf ${PXC_JOB_DIR}/config/disable_mysql_cli_history.sh /etc/profile.d/disable
 
 ulimit -n 1048576
 
-function check_mysql_disk_persistence() {
+check_mysql_disk_persistence() {
   if [[ (! -d /var/vcap/store) || $(mountpoint -d /var/vcap/store) == $(mountpoint -d /) ]]
   then
     err "Persistent disk not found"
@@ -113,7 +115,7 @@ function check_mysql_disk_persistence() {
   fi
 }
 
-function check_mysql_disk_capacity() {
+check_mysql_disk_capacity() {
   local datadir_capacity=$(df --block-size=1M --output=target,size /var/vcap/store | awk ' NR==2 { print $2 } ')
   local minimum_required_space_in_mb=5000
   if [[ "${datadir_capacity}" -lt "${minimum_required_space_in_mb}" ]]
@@ -139,9 +141,9 @@ if rmdir "${datadir}" 2> /dev/null; then
 fi
 
 if [ ! -d "${datadir}" ]; then
-  log "pre-start setup script: making ${datadir} and running /var/vcap/packages/percona-xtradb-cluster-<%= p('mysql_version') %>/bin/mysqld"
+  log "pre-start setup script: making ${datadir} and running /var/vcap/packages/percona-xtradb-cluster-${mysql_version}/bin/mysqld"
   mkdir -p ${datadir}
-  /var/vcap/packages/percona-xtradb-cluster-<%= p('mysql_version') %>/bin/mysqld \
+  "/var/vcap/packages/percona-xtradb-cluster-${mysql_version}/bin/mysqld" \
          --defaults-file=/var/vcap/jobs/pxc-mysql/config/my.cnf \
          --initialize
 fi
@@ -149,19 +151,24 @@ chown -R vcap:vcap ${datadir}
 
 rm -f /etc/my.cnf
 
-function check_bpm_pid {
+check_bpm_pid() {
     /var/vcap/jobs/bpm/bin/bpm pid pxc-mysql -p galera-init >/dev/null 2>&1
 }
 
 <%- if p('mysql_version') == "5.7" -%>
 /var/vcap/jobs/pxc-mysql/bin/mysql57_upgrade
 <%- end -%>
-<%- if p('mysql_version') == "8.0" -%>
-function is_pxc57_datadir {
+
+<%- if p('mysql_version') != "5.7" -%>
+is_pxc57_datadir() {
   [[ -f /var/vcap/store/pxc-mysql/mysql/user.frm ]]
 }
 
-function apply_pxc57_crash_recovery {
+is_pxc80_datadir() {
+  [[ -d "/var/vcap/store/pxc-mysql/#innodb_redo" && ! -f /var/vcap/store/pxc-mysql/mysql_upgrade_history ]]
+}
+
+apply_pxc57_crash_recovery() {
   local recovery_log=/var/vcap/sys/log/pxc-mysql/pxc-57-recovery.log
   if /var/vcap/packages/percona-xtradb-cluster-5.7/bin/mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --wsrep-recover --disable-log-error &> "${recovery_log}"; then
     log "pre-start: recovered percona-xtradb-cluster 5.7 data directory prior to upgrade"
@@ -171,9 +178,19 @@ function apply_pxc57_crash_recovery {
   fi
 }
 
+apply_pxc80_crash_recovery() {
+  local recovery_log=/var/vcap/sys/log/pxc-mysql/pxc-80-recovery.log
+  if /var/vcap/packages/percona-xtradb-cluster-8.0/bin/mysqld --wsrep-recover --disable-log-error &> "${recovery_log}"; then
+    log "pre-start: recovered percona-xtradb-cluster 8.0 data directory prior to upgrade"
+  else
+    log "pre-start: [FAIL] unable to recover percona-xtradb-cluster 8.0 data directory prior to upgrade"
+    log "pre-start: [FAIL] see ${recovery_log} for details."
+  fi
+}
+
 # Workaround for https://bugs.mysql.com/110702
 # This applies an extra restart of the local instance to perform an early upgrade before the main mysql server startup.
-function apply_mysql_bug_110702_workaround {
+apply_mysql_bug_110702_workaround() {
   if /var/vcap/packages/percona-xtradb-cluster-8.0/bin/mysqld --wsrep-recover; then # wsrep-recover for isolated single-node upgrade
     log "pre-start: applied initial upgrade to workaround https://bugs.mysql.com/110702"
   else
@@ -182,12 +199,18 @@ function apply_mysql_bug_110702_workaround {
   fi
 }
 
-if is_pxc57_datadir; then
+if is_pxc57_datadir && [[ ${mysql_version} == "8.4" ]]; then
+  log "pre-start: MySQL v5.7 data directory detected, but the target MySQL version is v8.4. Upgrade unsupported."
+  exit 1
+elif is_pxc57_datadir; then
   apply_pxc57_crash_recovery
   apply_mysql_bug_110702_workaround
-else
-  log "pre-start: skipping special percona-xtradb-cluster 5.7 upgrade logic. percona-xtradb-cluster 5.7 data directory not detected."
 fi
+
+if is_pxc80_datadir; then
+  apply_pxc80_crash_recovery
+fi
+
 <%- end -%>
 
 if ! /var/vcap/jobs/bpm/bin/bpm start pxc-mysql -p galera-init; then
